# Generated by Django 3.1 on 2020-08-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ad_published',
            field=models.BooleanField(default=False),
        ),
    ]
