# Generated by Django 3.1 on 2020-08-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_article_ad_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Ad_Part_link',
            field=models.URLField(blank=True, max_length=400, null=True),
        ),
    ]
